RedisExchangeAPI.Web/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Web.Services;
using StackExchange.Redis;
using System.Collections.Generic;
using System.Linq;

namespace RedisExchangeAPI.Web.Controllers
{
    public class ListTypeController : Controller
    {
        private readonly IDatabase db;

        private readonly RedisService _redisService;

        private string listKey = "names";

        public ListTypeController(RedisService redisService)
        {
            _redisService = redisService;
            this.db = _redisService.GetDb(0);
        }

        public IActionResult Index()
        {
            List<string> namesList = new List<string>();
            if (db.KeyExists(listKey))
            {
                db.ListRange(listKey).ToList().ForEach(x =>
                {
                    namesList.Add(x.ToString());
                });//eğer başlangıç ve bitiş değeri vermezsek baştan sona tüm dataları okur.
            }
            return View(namesList);
        }
        [HttpPost]
        public IActionResult Add(string name)
        {
            db.ListRightPush(listKey, name);

            return RedirectToAction("Index");
        }
        public IActionResult DeleteItem(string name)
        {
            db.ListRemoveAsync(listKey,name).Wait();
            return RedirectToAction("Index");
        }
        public IActionResult DeleteFirstItem()
        {
            db.ListLeftPopAsync(listKey).Wait();//left pop ile baştaki değeri siler.
            return RedirectToAction("Index");
        }
    }
}

RedisExchangeAPI.Web/Views/ListType/Index.cshtml
@model List<string>
@{
    ViewData["Title"] = "Index";
}

<!-- enctype -->
@*1) text/plain ---> Eğer dataların düz bir metin olarak gitmesini istiyorsak kullanırız. Tercih edilen bir yöntem değildir.
2) multipart/form-data ---> Eğer formun içerisinde input file tag'ini kullanıyorsak bunu kullanmalıyız.
3) application/x-www-form-urlencoded ---> Eğer dataların encode edilmesini istiyorsak kullanırız.
*@
<!-- #endregion -->

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Kaydet</button>
</form>

<hr />
<a asp-action="DeleteFirstItem">İlk değeri sil</a>
@foreach (var item in Model)
{
    <h2>@item <a asp-controller="ListType" asp-action="DeleteItem" asp-route-name="@item">Sil</a></h2>
}